# Update Ace editor with newest release
name: Update Ace

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Ace
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: acelib
      
      - name: Checkout ace-builds repo
        uses: actions/checkout@v3
        with:
          repository: ajaxorg/ace-builds
          path: ace-builds
          
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Use new Ace files
        run: |
          rm -rf acelib/scripts/library/
          mv ace-builds/src-min-noconflict/ acelib/scripts/library/

      - name: Find latest upstream tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ajaxorg/ace
          releases-only: true
        id: latestUpstream
        
      - name: Find latest tag for this repo
        uses: oprypin/find-latest-tag@v1
        with:
          repository: arcanistzed/acelib
          releases-only: true
        id: latestMain

      - name: Determine tag for this release
        uses: actions-ecosystem/action-bump-semver@v1
        id: newTag
        with:
          current_version: ${{ steps.latestMain.outputs.tag }}
          level: minor

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update ace to ${{ steps.latestUpstream.outputs.tag }}"
          cwd: "./acelib"

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          body: "Update Ace editor to ${{ steps.latestUpstream.outputs.tag }}"
          draft: true
          generateReleaseNotes: true
          tag: ${{ steps.newTag.outputs.new_version }}
